(async()=>{
const b=JSON.parse(localStorage.getItem('egw_invoice')||'null'),root=document.getElementById('invoice');
const rp=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0);
if(!b){root.innerHTML='<h2>Invoice tidak ditemukan</h2><p>Silakan buat booking terlebih dahulu.</p>';return}
let phone='';
try{const c=window.EGW_CONFIG||{};if(window.supabase&&!c.SUPABASE_URL.includes('YOUR-')){const sb=window.supabase.createClient(c.SUPABASE_URL,c.SUPABASE_ANON_KEY);const {data}=await sb.from('company_settings').select('phone').eq('id',1).maybeSingle();phone=data?.phone||''}}catch(e){}
function wa(n){let x=String(n||'').replace(/\D/g,'');if(x.startsWith('0'))x='62'+x.slice(1);return x}
const msg=`Halo Empayangindah.wisata, saya ingin melakukan pembayaran/konfirmasi booking.%0A%0AKode: ${b.code}%0ANama: ${b.name}%0ARute: ${b.route}%0ATanggal: ${b.date}%0AJam: ${b.departure||'-'}%0AJumlah: ${b.qty} penumpang%0ATotal: ${rp(b.total)}%0ATitik jemput: ${b.pickup||'-'}%0A%0AMohon informasi pembayaran. Terima kasih.`;
root.innerHTML=`<div class="invoice-head"><div class="invoice-brand"><img src="assets/images/logo.png" alt=""><div><strong>EMPAYANGINDAH<span class="gold">.WISATA</span></strong><p>Open Trip & Shuttle Bus</p></div></div><div><strong>INVOICE</strong><p>${b.code}</p></div></div><p><strong>Nama:</strong> ${b.name}<br><strong>WhatsApp:</strong> ${b.phone}<br><strong>Rute:</strong> ${b.route}<br><strong>Tanggal:</strong> ${b.date}<br><strong>Jam:</strong> ${b.departure||'-'}<br><strong>Jemput:</strong> ${b.pickup||'-'}</p><table><tr><th>Perjalanan</th><th>Qty</th><th>Harga</th><th>Total</th></tr><tr><td>${b.route}</td><td>${b.qty}</td><td>${rp(b.price)}</td><td>${rp(b.total)}</td></tr></table><div class="total">Total: ${rp(b.total)}</div><p>Status: <strong>${b.status}</strong></p><div class="hero-actions"><button class="btn primary" onclick="print()">Cetak Invoice</button><a class="btn primary" id="wa-pay" href="${phone?`https://wa.me/${wa(phone)}?text=${msg}`:'#'}" target="_blank" rel="noopener">Bayar / Konfirmasi via WhatsApp</a></div><p class="muted">Setelah pembayaran, kirim bukti pembayaran melalui WhatsApp agar admin dapat memverifikasi booking.</p>`;
})();
